DELETE http://localhost:3001/api/persons/635fb404ccda24d9af7d02e3
# REMOVE ONE USER (NOT FOUND ID -404)

###

DELETE http://localhost:3001/api/persons/KADFJLKSDJFLKSDJF
# REMOVE ONE USER (MISSPELLED ID - 500)

###

DELETE http://localhost:3001/api/persons/6360c5fdecd37233353439f0
# REMOVE ONE USER (OK)

###
