###############################################################

GET http://localhost:3001/api/persons
# GET ALL STORED PERSONS


###############################################################

GET http://localhost:3001/api/persons/6362a760aa442f97b50489e6
# GET SINGLE PERSON, BY ID (OK)


###############################################################

GET http://localhost:3001/api/persons/635f88e79e98438169c90eb3
# GET SINGLE PERSON, BY ID (NOT FOUND)


###############################################################

GET http://localhost:3001/api/persons/allkdsflksjflksjdfkljsdf
# GET SINGLE PERSON, BY ID (MALFORMATTED ID)