###############################################################

GET http://localhost:3001/api/persons
# GET ALL STORED PERSONS


###############################################################


POST http://localhost:3001/api/persons/
Content-Type: application/json

{
    "name": "Anastasia",
    "phone": "3329999999"
}



###

POST http://localhost:3001/api/persons/
Content-Type: application/json

{
    "name": "Laura",
    "phone": "45453"
}



###

POST http://localhost:3001/api/persons/
Content-Type: application/json

{
    "phone": "9845798345984537"
}



###



POST http://localhost:3001/api/persons/
Content-Type: application/json

{
    "name": "IN Correcto!222"
}